//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Resources.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bridge.
        /// </summary>
        internal static string FingerboardEnd_Bridge {
            get {
                return ResourceManager.GetString("FingerboardEnd_Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nut.
        /// </summary>
        internal static string FingerboardEnd_Nut {
            get {
                return ResourceManager.GetString("FingerboardEnd_Nut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bass.
        /// </summary>
        internal static string FingerboardSide_Bass {
            get {
                return ResourceManager.GetString("FingerboardSide_Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Treble.
        /// </summary>
        internal static string FingerboardSide_Treble {
            get {
                return ResourceManager.GetString("FingerboardSide_Treble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Simple line.
        /// </summary>
        internal static string LineRenderMode_PlainLine {
            get {
                return ResourceManager.GetString("LineRenderMode_PlainLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Realistic look.
        /// </summary>
        internal static string LineRenderMode_RealisticLook {
            get {
                return ResourceManager.GetString("LineRenderMode_RealisticLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Real width.
        /// </summary>
        internal static string LineRenderMode_RealWidth {
            get {
                return ResourceManager.GetString("LineRenderMode_RealWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All.
        /// </summary>
        internal static string Margins_All {
            get {
                return ResourceManager.GetString("Margins_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bass &amp; Treble.
        /// </summary>
        internal static string Margins_BassTreble {
            get {
                return ResourceManager.GetString("Margins_BassTreble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edges.
        /// </summary>
        internal static string Margins_Edges {
            get {
                return ResourceManager.GetString("Margins_Edges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nut &amp; Bridge.
        /// </summary>
        internal static string Margins_NutBridge {
            get {
                return ResourceManager.GetString("Margins_NutBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centered between fingerboard edges.
        /// </summary>
        internal static string StringSpacingAlignment_FingerboardEdges {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_FingerboardEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centered between middle strings.
        /// </summary>
        internal static string StringSpacingAlignment_MiddleStringEven {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_MiddleStringEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centered along middle string.
        /// </summary>
        internal static string StringSpacingAlignment_MiddleStringOdd {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_MiddleStringOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centered between outer strings.
        /// </summary>
        internal static string StringSpacingAlignment_OuterStrings {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_OuterStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equal distance (center to center).
        /// </summary>
        internal static string StringSpacingMethod_EqualDistance {
            get {
                return ResourceManager.GetString("StringSpacingMethod_EqualDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Equal spacing (between strings).
        /// </summary>
        internal static string StringSpacingMethod_EqualSpacing {
            get {
                return ResourceManager.GetString("StringSpacingMethod_EqualSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom.
        /// </summary>
        internal static string Words_CustomRatio {
            get {
                return ResourceManager.GetString("Words_CustomRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fret.
        /// </summary>
        internal static string Words_Fret {
            get {
                return ResourceManager.GetString("Words_Fret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Length.
        /// </summary>
        internal static string Words_Length {
            get {
                return ResourceManager.GetString("Words_Length", resourceCulture);
            }
        }
    }
}
