//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiGen.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localizations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localizations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiGen.Resources.Localizations", typeof(Localizations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file could not be found..
        /// </summary>
        internal static string Errors_FileNotFound {
            get {
                return ResourceManager.GetString("Errors_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while opening the file:.
        /// </summary>
        internal static string Errors_OpeningFile {
            get {
                return ResourceManager.GetString("Errors_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        internal static string FingerboardEnd_Bridge {
            get {
                return ResourceManager.GetString("FingerboardEnd_Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut.
        /// </summary>
        internal static string FingerboardEnd_Nut {
            get {
                return ResourceManager.GetString("FingerboardEnd_Nut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last fret.
        /// </summary>
        internal static string FingerboardMarginProperty_LastFret {
            get {
                return ResourceManager.GetString("FingerboardMarginProperty_LastFret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass.
        /// </summary>
        internal static string FingerboardSide_Bass {
            get {
                return ResourceManager.GetString("FingerboardSide_Bass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treble.
        /// </summary>
        internal static string FingerboardSide_Treble {
            get {
                return ResourceManager.GetString("FingerboardSide_Treble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left handed.
        /// </summary>
        internal static string Layout_LeftHanded {
            get {
                return ResourceManager.GetString("Layout_LeftHanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of frets.
        /// </summary>
        internal static string LayoutProperty_NumberOfFrets {
            get {
                return ResourceManager.GetString("LayoutProperty_NumberOfFrets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of strings.
        /// </summary>
        internal static string LayoutProperty_NumberOfStrings {
            get {
                return ResourceManager.GetString("LayoutProperty_NumberOfStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length mode.
        /// </summary>
        internal static string LayoutProperty_ScaleLengthMode {
            get {
                return ResourceManager.GetString("LayoutProperty_ScaleLengthMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String spacing mode.
        /// </summary>
        internal static string LayoutProperty_StringSpacingMode {
            get {
                return ResourceManager.GetString("LayoutProperty_StringSpacingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple line.
        /// </summary>
        internal static string LineRenderMode_PlainLine {
            get {
                return ResourceManager.GetString("LineRenderMode_PlainLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Realistic look.
        /// </summary>
        internal static string LineRenderMode_RealisticLook {
            get {
                return ResourceManager.GetString("LineRenderMode_RealisticLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real width.
        /// </summary>
        internal static string LineRenderMode_RealWidth {
            get {
                return ResourceManager.GetString("LineRenderMode_RealWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Margins_All {
            get {
                return ResourceManager.GetString("Margins_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass &amp; Treble.
        /// </summary>
        internal static string Margins_BassTreble {
            get {
                return ResourceManager.GetString("Margins_BassTreble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        internal static string Margins_Edges {
            get {
                return ResourceManager.GetString("Margins_Edges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut &amp; Bridge.
        /// </summary>
        internal static string Margins_NutBridge {
            get {
                return ResourceManager.GetString("Margins_NutBridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Messages_Error {
            get {
                return ResourceManager.GetString("Messages_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected file is already open.
        ///Do you want to reload it? 
        ///(All changes will be lost).
        /// </summary>
        internal static string Messages_FileAlreadyOpen {
            get {
                return ResourceManager.GetString("Messages_FileAlreadyOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid export format..
        /// </summary>
        internal static string Messages_InvalidExportFormat {
            get {
                return ResourceManager.GetString("Messages_InvalidExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file.
        /// </summary>
        internal static string Messages_OpeningFile {
            get {
                return ResourceManager.GetString("Messages_OpeningFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the changes made to the layout before closing?.
        /// </summary>
        internal static string Messages_SaveBeforeClosing {
            get {
                return ResourceManager.GetString("Messages_SaveBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Messages_Warning {
            get {
                return ResourceManager.GetString("Messages_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        internal static string Misc_AllFilesDesc {
            get {
                return ResourceManager.GetString("Misc_AllFilesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiGen Layout file.
        /// </summary>
        internal static string Misc_LayoutFileDesc {
            get {
                return ResourceManager.GetString("Misc_LayoutFileDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New layout.
        /// </summary>
        internal static string Misc_NewLayout {
            get {
                return ResourceManager.GetString("Misc_NewLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dual.
        /// </summary>
        internal static string ScaleLengthType_Dual {
            get {
                return ResourceManager.GetString("ScaleLengthType_Dual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        internal static string ScaleLengthType_Multiple {
            get {
                return ResourceManager.GetString("ScaleLengthType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string ScaleLengthType_Single {
            get {
                return ResourceManager.GetString("ScaleLengthType_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String properties.
        /// </summary>
        internal static string StringProperties {
            get {
                return ResourceManager.GetString("StringProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gauge.
        /// </summary>
        internal static string StringProperty_Gauge {
            get {
                return ResourceManager.GetString("StringProperty_Gauge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting fret.
        /// </summary>
        internal static string StringProperty_StartingFret {
            get {
                return ResourceManager.GetString("StringProperty_StartingFret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered between fingerboard edges.
        /// </summary>
        internal static string StringSpacingAlignment_FingerboardEdges {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_FingerboardEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered between middle strings.
        /// </summary>
        internal static string StringSpacingAlignment_MiddleStringEven {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_MiddleStringEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered along middle string.
        /// </summary>
        internal static string StringSpacingAlignment_MiddleStringOdd {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_MiddleStringOdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centered between outer strings.
        /// </summary>
        internal static string StringSpacingAlignment_OuterStrings {
            get {
                return ResourceManager.GetString("StringSpacingAlignment_OuterStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal distance (center to center).
        /// </summary>
        internal static string StringSpacingMethod_EqualDistance {
            get {
                return ResourceManager.GetString("StringSpacingMethod_EqualDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal spacing (between strings).
        /// </summary>
        internal static string StringSpacingMethod_EqualSpacing {
            get {
                return ResourceManager.GetString("StringSpacingMethod_EqualSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge alignment.
        /// </summary>
        internal static string StringSpacingProperty_BridgeAlignment {
            get {
                return ResourceManager.GetString("StringSpacingProperty_BridgeAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nut alignment.
        /// </summary>
        internal static string StringSpacingProperty_NutAlignment {
            get {
                return ResourceManager.GetString("StringSpacingProperty_NutAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing.
        /// </summary>
        internal static string StringSpacingProperty_Spacing {
            get {
                return ResourceManager.GetString("StringSpacingProperty_Spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing mode.
        /// </summary>
        internal static string StringSpacingProperty_SpacingMode {
            get {
                return ResourceManager.GetString("StringSpacingProperty_SpacingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string StringSpacingType_Manual {
            get {
                return ResourceManager.GetString("StringSpacingType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string StringSpacingType_Simple {
            get {
                return ResourceManager.GetString("StringSpacingType_Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        internal static string Words_CustomRatio {
            get {
                return ResourceManager.GetString("Words_CustomRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fret.
        /// </summary>
        internal static string Words_Fret {
            get {
                return ResourceManager.GetString("Words_Fret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Words_Length {
            get {
                return ResourceManager.GetString("Words_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        internal static string Words_Margins {
            get {
                return ResourceManager.GetString("Words_Margins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpendicular fret.
        /// </summary>
        internal static string Words_PerpendicularFret {
            get {
                return ResourceManager.GetString("Words_PerpendicularFret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale length.
        /// </summary>
        internal static string Words_ScaleLength {
            get {
                return ResourceManager.GetString("Words_ScaleLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        internal static string Words_String {
            get {
                return ResourceManager.GetString("Words_String", resourceCulture);
            }
        }
    }
}
